language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install: 
    - pip install -r web/requirements.txt
    - pip install python-coveralls
script:
    - nosetests --with-coverage --cover-package=pysal
after_success:  
    - coveralls 